import type { Course } from "./types"

export const courseData: Course[] = [
  // Foundation Level - Data Science
  {
    id: "mds1",
    name: "Mathematics 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "eng1",
    name: "English 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ct",
    name: "Computational Thinking",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "stats1",
    name: "Statistics 1",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Marks (applied if base score >= 40)", max: 5 },
    ],
  },
  {
    id: "stats2",
    name: "Statistics 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Marks (applied if base score >= 40)", max: 5 },
    ],
  },
  {
    id: "mds2",
    name: "Mathematics 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Marks (max 6)", max: 6 },
    ],
  },
  {
    id: "eng2",
    name: "English 2",
    degree: "data-science",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "python",
    name: "Python Programming",
    degree: "data-science",
    level: "foundation",
    formula: "T = 0.15 * Qz1 + 0.4 * F + 0.25 * max(PE1, PE2) + 0.2 * min(PE1, PE2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "PE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "PE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
    ],
  },

  // Diploma Level - Data Science
  {
    id: "mlf",
    name: "Machine Learning Foundations",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlt",
    name: "Machine Learning Techniques",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "ProgrammingBonus", label: "Programming Bonus", description: "Bonus Marks (max 3, applied if GAA >= 40)", max: 3 },
    ],
  },
  {
    id: "mlp",
    name: "Machine Learning Practice",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.3 * F + 0.2 * OPPE1 + 0.2 * OPPE2 + 0.2 * KA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "KA", label: "KA", description: "Kaggle Assignment score", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bdm",
    name: "Business Data Management",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ban",
    name: "Business Analytics",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.4 * (0.7 * max(Qz1, Qz2) + 0.3 * min(Qz1, Qz2)) + 0.2 * A + 0.4 * F",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "A", label: "Assignments", description: "Assignment Score (Sum of best 2 out of 3)", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "tds",
    name: "Tools in Data Science",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.2 * GAA + 0.2 * ROE + 0.2 * P1 + 0.2 * P2 + 0.2 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average (best 7 of 9)", max: 100 },
      { id: "ROE", label: "ROE", description: "Remote Online Exam Score", max: 100 },
      { id: "P1", label: "Project 1", description: "Take home project 1 Score", max: 100 },
      { id: "P2", label: "Project 2", description: "Take home project 2 Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dl-genAI",
    name: "Intro to DL and GenAI",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.1 * GAA + 0.2 * Qz1 + 0.2 * Qz2 + 0.25 * F + 0.1 * NPPE1 + 0.15 * NPPE2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz 1", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "NPPE1", label: "NPPE 1", description: "Non-Proctored Programming Exam 1", max: 100 },
      { id: "NPPE2", label: "NPPE 2", description: "Non-Proctored Programming Exam 2", max: 100 },
    ],
  },
  {
    id: "pds",
    name: "PDSA",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + 0.2 * OP + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "OP", label: "OP", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dbms",
    name: "DBMS",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.03 * GAA2 + 0.02 * GAA3 + 0.2 * OP + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2)",
    formFields: [
      { id: "GAA2", label: "GAA 2", description: "Graded Assignment 2", max: 100 },
      { id: "GAA3", label: "GAA 3", description: "Graded Assignment 3", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "OP", label: "OP", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ad1",
    name: "AppDev-1",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GLA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GLA", label: "GLA", description: "Graded Lab Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "java",
    name: "Programming Concepts using Java",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + 0.2 * max(PE1, PE2) + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2) + 0.1 * min(PE1, PE2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "PE1", label: "PE 1", description: "Programming Exam 1", max: 100 },
      { id: "PE2", label: "PE 2", description: "Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sys",
    name: "System Commands",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + 0.25 * Qz1 + 0.3 * OPPE + 0.3 * F + 0.1 * BPTA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "OPPE", label: "OPPE", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "BPTA", label: "BPTA", description: "Biweekly Programming Test Average", max: 100 },
    ],
  },
  {
    id: "ad2",
    name: "AppDev-2",
    degree: "data-science",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  // Degree Level - Data Science
  {
    id: "st",
    name: "Software Testing",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "se",
    name: "Software Engineering",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.2 * Qz2 + 0.4 * F + 0.1 * GP1 + 0.1 * GP2 + 0.1 * PP + 0.05 * CP",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "GP1", label: "Group Project 1", description: "First Group Project Score", max: 100 },
      { id: "GP2", label: "Group Project 2", description: "Second Group Project Score", max: 100 },
      { id: "PP", label: "Peer Performance", description: "Peer Performance Score", max: 100 },
      { id: "CP", label: "Class Participation", description: "Class Participation Score", max: 100 },
    ],
  },
  {
    id: "dl",
    name: "Deep Learning",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.25 * Qz1 + 0.25 * Qz2 + 0.45 * F + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "ProgrammingBonus", label: "Programming Bonus", description: "Programming Activity Bonus Marks (max 5)", max: 5 },
    ],
  },
  {
    id: "ai-search",
    name: "AI: Search Methods for Problem Solving",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "ProgrammingBonus", label: "Bonus", description: "Programming Assignment Bonus (max 5, if passed)", max: 5 },
    ],
  },
  {
    id: "llm",
    name: "Large Language Models",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.35 * F + 0.3 * Qz1 + 0.3 * Qz2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Programming Assignment Bonus (max 5, if passed)", max: 5 },
    ],
  },

  {
    id: "spg",
    name: "Strategies for Professional Growth",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.15 * GAA + 0.25 * GP + 0.25 * Qz2 + 0.35 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GP", label: "Group Project", description: "Group Project Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ibd",
    name: "Introduction to Big Data",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.3 * F + 0.2 * OPPE1 + 0.4 * OPPE2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dlcv",
    name: "Deep Learning for CV",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Optional Project Bonus (max 5)", max: 5 },
    ],
  },
  {
    id: "dv",
    name: "Data Visualization Design",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.3 * GA + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2)) + 0.3 * P + Bonus",
    formFields: [
      { id: "GA", label: "GA", description: "Graded Assignments", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "P", label: "Project", description: "Project Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Marks (max 5)", max: 5 },
    ],
  },
  {
    id: "me",
    name: "Managerial Economics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "atb",
    name: "Algorithmic Thinking in Bioinformatics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.075 * GAA + 0.025 * GAAP + 0.25 * Qz1 + 0.25 * Qz2 + 0.4 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GAAP", label: "GAAP", description: "Graded Assignment Autograded Programming", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "i4",
    name: "Industry 4.0",
    degree: "data-science",
    level: "degree",
    formula: "T = A + 0.3 * F + 0.15 * (Qz1 + Qz2) + 0.05 * Game + 0.1 * Project",
    formFields: [
      { id: "A", label: "Assignments", description: "Best 2 out of 3 Assignments", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Game", label: "Game", description: "Game Score", max: 100 },
      { id: "Project", label: "Project", description: "Project Score", max: 100 },
    ],
  },
  {
    id: "mt",
    name: "Mathematical Thinking",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "lsm",
    name: "Linear Statistical Models",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2) + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "NormalBonus", label: "Bonus", description: "Bonus Marks (applied if total >= 40)", max: 10 },
    ],
  },
  {
    id: "cprog",
    name: "Programming in C",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.2 * Qz1 + 0.2 * OPPE1 + 0.2 * OPPE2 + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Practice Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Practice Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ff",
    name: "Financial Forensics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.25 * Qz1 + 0.30 * GP1 + 0.35 * F, 0.5 * F + 0.3 * max(Qz1, GP1))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "GP1", label: "Group Project 1", description: "First Group Project Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "nlp",
    name: "Introduction to Natural Language Processing",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.5 * F + 0.2 * Qz1 + 0.2 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cf",
    name: "Corporate Finance",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dlp",
    name: "Deep Learning Practice",
    degree: "data-science",
    level: "degree",
    formula:
      "T = 0.05 * GA + 0.15 * Quiz1 + 0.15 * Quiz2 + 0.15 * Quiz3 + 0.25 * ((NPPE1 + NPPE2 + NPPE3)/3) + 0.25 * Viva",
    formFields: [
      { id: "GA", label: "GA", description: "Graded Assignment Average", max: 100 },
      { id: "Quiz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Quiz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "Quiz3", label: "Quiz 3", description: "Third Quiz Score", max: 100 },
      { id: "NPPE1", label: "NPPE 1", description: "Non-Proctored Exam 1 Score", max: 100 },
      { id: "NPPE2", label: "NPPE 2", description: "Non-Proctored Exam 2 Score", max: 100 },
      { id: "NPPE3", label: "NPPE 3", description: "Non-Proctored Exam 3 Score", max: 100 },
      { id: "Viva", label: "Viva", description: "Viva Score", max: 100 },
    ],
  },
  {
    id: "os",
    name: "Operating Systems",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "stml",
    name: "Special Topics in ML (Reinforcement Learning)",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.2 * GPA + max(0.2 * Qz1 + 0.2 * Qz2, 0.3 * max(Qz1, Qz2)) + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GPA", label: "GPA", description: "Graded Project Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bdbn",
    name: "Big Data & Biological Networks",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.15 * GAA + max(0.2 * Qz1 + 0.2 * Qz2 + 0.45 * F, 0.5 * F + 0.25 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dsai-lab",
    name: "Data Science and AI Lab",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.25 * Quiz + 0.4 * P + 0.3 * V + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Quiz", label: "Quiz", description: "Quiz Score", max: 100 },
      { id: "P", label: "Project", description: "Project Presentation & Milestones", max: 100 },
      { id: "V", label: "Viva", description: "Viva Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Marks (max 5)", max: 5 },
    ],
  },
  {
    id: "appdev-lab",
    name: "Application Development Lab",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.3 * GAA + 0.2 * Qz2 + 0.5 * V",
    formFields: [
      { id: "GAA", label: "GAA", description: "Weekly Assignments Average", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score", max: 100 },
      { id: "V", label: "Project Viva", description: "Project Viva Score", max: 100 },
    ],
  },
  {
    id: "mr",
    name: "Market Research",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.2 * Qz1 + 0.2 * Qz2 + 0.25 * P + 0.25 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "P", label: "Project", description: "Open-ended Project Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlops",
    name: "MLOps (Machine Learning Operations)",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.2 * GAA + 0.3 * F + 0.25 * OPPE1 + 0.25 * OPPE2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Proctored Programming Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Proctored Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Active Course Participation Bonus (max 5)", max: 5 },
    ],
  },
  {
    id: "mf-genAI",
    name: "Mathematical Foundations of Generative AI",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.35 * F + 0.2 * Qz1 + 0.2 * Qz2 + 0.2 * NPPE",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "NPPE", label: "NPPE", description: "Non-Proctored Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dt-appdev",
    name: "Design Thinking for Data-Driven App Development",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.1 * GP1 + 0.1 * GP2 + 0.2 * GP3 + 0.2 * Qz2 + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GP1", label: "GP 1", description: "Group Project Milestone 1", max: 100 },
      { id: "GP2", label: "GP 2", description: "Group Project Milestone 2", max: 100 },
      { id: "GP3", label: "GP 3", description: "Group Project Milestone 3", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ps-osm",
    name: "Privacy & Security in Online Social Media",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.2 * GAA + 0.3 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cs-design",
    name: "Computer Systems Design",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.2 * Qz1 + 0.25 * Qz2 + 0.05 * CVA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "CVA", label: "CVA", description: "Circuit Verse Assignment", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "gts",
    name: "Game Theory and Strategy",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ads",
    name: "Algorithms for Data Science (ADS)",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.1 * PAA + 0.45 * F + 0.35 * Qz2 + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Theory Assignments Average", max: 100 },
      { id: "PAA", label: "PAA", description: "Programming Assignments Average", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Bonus Questions Marks (max 4)", max: 4 },
    ],
  },
  {
    id: "dm",
    name: "Discrete Mathematics",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cd",
    name: "Compiler Design",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "toc",
    name: "Theory of Computation",
    degree: "data-science",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  // Add here Electronic System courses after the existing Data Science courses

  // Foundation Level - Electronic Systems
  {
    id: "eng1-es",
    name: "English - I",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "math-elec1",
    name: "Math for Electronics - I",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "estc",
    name: "Electronic Systems Thinking and Circuits",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "estc-lab",
    name: "Electronic Systems Thinking and Circuits Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.5 * experiment + 0.5 * Report",
    formFields: [
      { id: "experiment", label: "Experiment", description: "Experiment Score", max: 100 },
      { id: "Report", label: "Report", description: "Report Score", max: 100 },
    ],
  },
  {
    id: "c-prog",
    name: "Introduction to C Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.25 * Qz1 + 0.45 * F + max(0.15 * OPPE1 + 0.15 * OPPE2, 0.20 * max(OPPE1, OPPE2))",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "Quiz 1 Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Exam 2", max: 100 },
    ],
  },
  {
    id: "c-prog-lab",
    name: "Introduction to C Programming Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.5 * (TLA) + 0.5 * (IL)",
    formFields: [
      { id: "TLA", label: "TLA", description: "Timed Lab Assignment Average", max: 100 },
      { id: "IL", label: "IL", description: "In-campus Lab Score", max: 100 },
    ],
  },
  {
    id: "eng2-es",
    name: "English - II",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "linux-prog",
    name: "Introduction to Linux Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.25 * Qz1 + 0.25 * OPPE + 0.35 * F + 0.1 * BPTA + 0.05 * VMT",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "OPPE", label: "OPPE", description: "Online Programming Exam", max: 100 },
      { id: "F", label: "Final Exam", description: "End Term Exam Score", max: 100 },
      { id: "BPTA", label: "BPTA", description: "Biweekly Programming Test Average", max: 100 },
      { id: "VMT", label: "VMT", description: "Virtual Machine Tasks Average", max: 100 },
    ],
  },
  {
    id: "linux-shell-lab",
    name: "Introduction to the Linux Shell Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.5 * (OL) + 0.5 * (IL)",
    formFields: [
      { id: "OL", label: "OL", description: "Online Lab Average", max: 100 },
      { id: "IL", label: "IL", description: "In-campus Lab Score", max: 100 },
    ],
  },
  {
    id: "digital-systems",
    name: "Digital Systems",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "elec-circuits",
    name: "Electrical and Electronic Circuits",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Tutorial Submission Bonus", max: 3 },
    ],
  },
  {
    id: "electronics-lab",
    name: "Electronics Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments Average", max: 100 },
      { id: "ID", label: "ID", description: "In-person Demonstration Score", max: 100 },
    ],
  },
  {
    id: "embedded-c",
    name: "Embedded C Programming",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.1 * GRPA + max((0.5 * F + 0.3 * max(Qz1, Qz2)), (0.4 * F + 0.25 * Qz1 + 0.25 * Qz2))",
    formFields: [
      { id: "GRPA", label: "GRPA", description: "Programming Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "embedded-c-lab",
    name: "Embedded C Programming Lab",
    degree: "electronic-systems",
    level: "foundation",
    formula: "T = 0.2 * (Attendance) + 0.8 * (LabExperiment)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score (100 if present)", max: 100 },
      { id: "LabExperiment", label: "Lab Experiment", description: "Lab Experiment and Viva Score", max: 100 },
    ],
  },

  // Diploma Level - Electronic Systems
  {
    id: "signals-systems",
    name: "Signals and Systems",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.5 * F + 0.25 * max(Qz1, Qz2), 0.45 * F + 0.2 * Qz1 + 0.2 * Qz2) + 0.1 * GrPA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "GrPA", label: "GrPA", description: "Best 4 out of 5 Programming Assignments", max: 100 },
    ],
  },
  {
    id: "python-es",
    name: "Python Programming",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA1 + 0.05 * GAA2 + 0.15 * Qz1 + 0.45 * F + 0.25 * max(PE1, PE2) + 0.15 * min(PE1, PE2)",
    formFields: [
      { id: "GAA1", label: "GAA 1", description: "Objective Assignment Average", max: 100 },
      { id: "GAA2", label: "GAA 2", description: "Programming Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "PE1", label: "PE 1", description: "OPPE 1 Score", max: 100 },
      { id: "PE2", label: "PE 2", description: "OPPE 2 Score", max: 100 },
    ],
  },
  {
    id: "analog-systems",
    name: "Analog Electronic Systems",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "analog-lab",
    name: "Analog Electronics Lab",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments Average", max: 100 },
      { id: "ID", label: "ID", description: "In-person Demonstration Score", max: 100 },
    ],
  },
  {
    id: "dsp",
    name: "Digital Signal Processing",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + 0.1 * LE + 0.05 * OLEx + max(0.55 * F + 0.15 * max(Qz1, Qz2), 0.5 * F + 0.15 * Qz1 + 0.15 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "LE", label: "LE", description: "Lab Experiments Average", max: 100 },
      { id: "OLEx", label: "OLEx", description: "Online Lab Exam Score", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sensors",
    name: "Sensors and Application",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sensors-lab",
    name: "Sensors Laboratory",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments Average", max: 100 },
      { id: "ID", label: "ID", description: "In-person Demonstration Score", max: 100 },
    ],
  },
  {
    id: "digital-system-design",
    name: "Digital System Design",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.5 * F + 0.2 * Qz1 + 0.25 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digital-system-lab",
    name: "Digital System Design Laboratory",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.4 * (WE) + 0.6 * (ID)",
    formFields: [
      { id: "WE", label: "WE", description: "Weekly Experiments Average", max: 100 },
      { id: "ID", label: "ID", description: "In-person Demonstration Score", max: 100 },
    ],
  },
  {
    id: "computer-org",
    name: "Computer Organization",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.5 * F + 0.2 * Qz1 + 0.25 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "electronic-testing",
    name: "Electronic Testing and Measurement",
    degree: "electronic-systems",
    level: "diploma",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.5 * F + 0.2 * Qz1 + 0.2 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },

  // Degree Level - Electronic Systems
  {
    id: "control-eng",
    name: "Control Engineering",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.45 * F + 0.2 * Qz1 + 0.2 * Qz2 + 0.05 * D",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "D", label: "Design Assignment", description: "Matlab Design Assignment", max: 100 },
    ],
  },
  {
    id: "em-fields",
    name: "Electromagnetic Fields and Transmission Lines",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "epd",
    name: "Electronic Product Design",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.3 * GAA + 0.2 * (Qz1 + Qz2) + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz 1 Score (converted out of 100)", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score (converted out of 100)", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "spg-es",
    name: "Strategies for Professional Growth",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.15 * GAA + 0.25 * GP + 0.25 * Qz2 + 0.35 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GP", label: "GP", description: "Group Project Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "embedded-linux",
    name: "Embedded Linux and FPGAs",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.5 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "embedded-linux-lab",
    name: "Embedded Linux and FPGAs Lab",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.2 * (Attendance) + 0.8 * (LabExperiment)",
    formFields: [
      { id: "Attendance", label: "Attendance", description: "Attendance Score (100 if present)", max: 100 },
      { id: "LabExperiment", label: "Lab Experiment", description: "Lab Experiment and Viva Score", max: 100 },
    ],
  },
  {
    id: "math-elec2",
    name: "Math for Electronics - II",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digital-ic",
    name: "Digital IC Design",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.3 * P + max(0.3 * F + 0.2 * max(Qz1, Qz2), 0.3 * F + 0.15 * Qz1 + 0.15 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "P", label: "Project", description: "Course Project Score", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "comm-systems",
    name: "Communication Systems",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "analog-circuits",
    name: "Analog Circuits",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "vlsi",
    name: "Semiconductor Devices and VLSI Technology",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlf-es",
    name: "Machine Learning Foundations",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dbms-es",
    name: "Database Management System (DBMS)",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.03 * GAA2 + 0.02 * GAA3 + 0.2 * OP + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2)",
    formFields: [
      { id: "GAA2", label: "GAA 2", description: "SQL Assignments Average (Weeks 2, 3)", max: 100 },
      { id: "GAA3", label: "GAA 3", description: "Programming Assignment Score (Week 7)", max: 100 },
      { id: "OP", label: "OPPE", description: "Online Proctored Exam Score", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "pdsa-es",
    name: "Programming Data Structures and Algorithms using Python",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.2 * OP + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "OP", label: "OPPE", description: "Online Proctored Exam Score", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "java-es",
    name: "Programming Concepts using Java",
    degree: "electronic-systems",
    level: "degree",
    formula:
      "T = 0.05 * GAA + 0.2 * max(PE1, PE2) + 0.45 * F + max(0.2 * max(Qz1, Qz2), 0.1 * Qz1 + 0.2 * Qz2) + 0.1 * min(PE1, PE2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Best 6 out of 7 Programming Assignments", max: 100 },
      { id: "PE1", label: "PE 1", description: "Online Proctored Exam 1", max: 100 },
      { id: "PE2", label: "PE 2", description: "Online Proctored Exam 2", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "appdev1-es",
    name: "Application Development - I",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GLA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GLA", label: "GLA", description: "Graded Lab Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "appdev2-es",
    name: "Application Development - II",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Programming Assignments Average (Weeks 1 & 2)", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mlt-es",
    name: "Machine Learning Techniques",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Programming Assignment Bonus", max: 3 },
    ],
  },
  {
    id: "mlp-es",
    name: "Machine Learning Practice",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.3 * F + 0.2 * OPPE1 + 0.2 * OPPE2 + 0.2 * KA",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Programming Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Programming Exam 2", max: 100 },
      { id: "KA", label: "KA", description: "Kaggle Assignments Average", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dl-es",
    name: "Deep Learning",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.25 * Qz1 + 0.25 * Qz2 + 0.45 * F + Bonus",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Programming Activity Bonus", max: 5 },
    ],
  },
  {
    id: "dlcv-es",
    name: "Deep Learning for CV",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "dlp-es",
    name: "Deep Learning Practice",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.05 * GAA + 0.15 * Qz1 + 0.15 * Qz2 + 0.15 * Qz3 + 0.25 * ((NPPE1 + NPPE2 + NPPE3) / 3) + 0.25 * Viva",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "Quiz 1 Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score", max: 100 },
      { id: "Qz3", label: "Quiz 3", description: "Quiz 3 Score", max: 100 },
      { id: "NPPE1", label: "NPPE 1", description: "Non-proctored Programming Exam 1", max: 100 },
      { id: "NPPE2", label: "NPPE 2", description: "Non-proctored Programming Exam 2", max: 100 },
      { id: "NPPE3", label: "NPPE 3", description: "Non-proctored Programming Exam 3", max: 100 },
      { id: "Viva", label: "Viva", description: "Viva Score", max: 100 },
    ],
  },
  {
    id: "dt-appdev-es",
    name: "Design Thinking for Data-Driven App Development",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.1 * GP1 + 0.1 * GP2 + 0.2 * GP3 + 0.2 * Qz2 + 0.3 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "GP1", label: "GP 1", description: "Group Project Milestone 1", max: 100 },
      { id: "GP2", label: "GP 2", description: "Group Project Milestone 2", max: 100 },
      { id: "GP3", label: "GP 3", description: "Group Project Milestone 3", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Quiz 2 Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mr-es",
    name: "Market Research",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.2 * Qz1 + 0.2 * Qz2 + 0.25 * P + 0.25 * F",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "P", label: "Project", description: "Open-ended Project Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "me-es",
    name: "Managerial Economics",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.15 * GAA + max(0.2 * Qz1 + 0.2 * Qz2 + 0.45 * F, 0.5 * F + 0.25 * max(Qz1, Qz2))",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "gts-es",
    name: "Game Theory and Strategy",
    degree: "electronic-systems",
    level: "degree",
    formula: "T = 0.1 * GAA + 0.4 * F + 0.25 * Qz1 + 0.25 * Qz2",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  // Aeronautics and Space Technology - Foundation Level
  {
    id: "eng1-ae",
    name: "English I",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "math-elec1-ae",
    name: "Math for Electronics I",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "estc-ae",
    name: "Electronic Systems Thinking and Circuits",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "c-prog-ae",
    name: "Introduction to C Programming",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = 0.25 * Qz1 + 0.45 * F + max(0.15 * OPPE1 + 0.15 * OPPE2, 0.20 * max(OPPE1, OPPE2))",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "In-center Quiz 1", max: 100 },
      { id: "OPPE1", label: "OPPE 1", description: "Online Proctored Programming Exam 1", max: 100 },
      { id: "OPPE2", label: "OPPE 2", description: "Online Proctored Programming Exam 2", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "eng2-ae",
    name: "English II",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "math-elec2-ae",
    name: "Math for Electronics II",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Average score in First 10 weekly graded assignments", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "intro-aero-ae",
    name: "Introduction to Aerospace Systems",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "eng-mech-ae",
    name: "Engineering Mechanics",
    degree: "aeronautics",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  // Management and Data Science - Foundation Level
  {
    id: "math1-mg",
    name: "Mathematics for Data Science I",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "stats1-mg",
    name: "Statistics for Data Science I",
    degree: "management",
    level: "foundation",
    formula: "T = min(100, max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2) + Bonus)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "Bonus", label: "Bonus", description: "Extra activity bonus marks (capped to 5)", max: 5 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ct-mg",
    name: "Computational Thinking",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "eng1-mg",
    name: "English I",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "econ-mg",
    name: "Principles of Economics",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "fin-acc-mg",
    name: "Financial Accounting",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bus-stats-mg",
    name: "Business Statistics",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mtp-mg",
    name: "Management Thought and Practice",
    degree: "management",
    level: "foundation",
    formula: "T = max(0.6 * F + 0.3 * max(Qz1, Qz2), 0.45 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  // Management and Data Science - Diploma Level
  {
    id: "py-da-mg",
    name: "Python for Data Analytics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "data-mgmt-mg",
    name: "Data Management",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "econ-data-mg",
    name: "Analysis of Economic Data",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mkt-analytics-mg",
    name: "Marketing Analytics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "hr-analytics-mg",
    name: "HR Analytics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "fin-analytics-mg",
    name: "Financial Analytics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ops-mgmt-mg",
    name: "Operations Management",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sc-analytics-mg",
    name: "Supply Chain Analytics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bm-proj-mg",
    name: "Business Management Project",
    degree: "management",
    level: "diploma",
    formula: "T = 0.5 * Report + 0.5 * F",
    formFields: [
      { id: "Report", label: "Report", description: "Project Report Score", max: 100 },
      { id: "F", label: "Final Viva", description: "Final Viva and Presentation Score", max: 100 },
    ],
  },
  {
    id: "ba-proj-mg",
    name: "Business Analytics Project",
    degree: "management",
    level: "diploma",
    formula: "T = 0.5 * Report + 0.5 * F",
    formFields: [
      { id: "Report", label: "Report", description: "Project Report Score", max: 100 },
      { id: "F", label: "Final Viva", description: "Final Viva and Presentation Score", max: 100 },
    ],
  },
  {
    id: "corp-fin-mg",
    name: "Corporate Finance",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "org-behav-mg",
    name: "Organisational Behavior",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "money-bank-mg",
    name: "Money, Banking and Financial Markets",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mkt-mgmt-mg",
    name: "Marketing Management",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "macro-econ-mg",
    name: "Macroeconomics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mgr-econ-mg",
    name: "Managerial Economics",
    degree: "management",
    level: "diploma",
    formula: "T = 0.05 * GAA + max(0.6 * F + 0.25 * max(Qz1, Qz2), 0.4 * F + 0.25 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  // Management and Data Science - Degree Level
  {
    id: "spg-mg",
    name: "Strategies for Professional Growth",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "genai-bus-mg",
    name: "GenAI for Business",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digi-bus-mg",
    name: "Digital Business",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "scm-mg",
    name: "Logistics and Supply Chain Management",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ts-analysis-mg",
    name: "Applied Time Series Analysis",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "mkt-intel-mg",
    name: "Market Intelligence",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "game-theory-mg",
    name: "Introduction to Game Theory",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "pub-fin-mg",
    name: "Public Finance",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "econ-ai-mg",
    name: "Economics of AI",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "ind-org-mg",
    name: "Industrial Organisation",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "res-design-mg",
    name: "Research Design for Social Data Science",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "proj-fin-mg",
    name: "Project Finance",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "corp-val-mg",
    name: "Corporate Valuation",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "fin-forensics-mg",
    name: "Financial Forensics",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "alm-risk-mg",
    name: "ALM and Risk",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "cap-markets-mg",
    name: "Capital Markets and Derivatives",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digi-mkt-mg",
    name: "Digital Marketing",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "brand-mgmt-mg",
    name: "Brand Management",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "consumer-behav-mg",
    name: "Consumer Behavior",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "design-think-mg",
    name: "Design Thinking",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "comp-opt-mg",
    name: "Computational Optimization",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "bus-res-mg",
    name: "Business Research Methods",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "sust-bus-mg",
    name: "Sustainable Business Models",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "digi-strat-mg",
    name: "Digital Business Strategy and Models",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "fam-bus-mg",
    name: "Family Business",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "soc-media-mg",
    name: "Social Media Computing",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "perf-mgmt-mg",
    name: "Performance Management",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
  {
    id: "resp-ai-mg",
    name: "Responsible AI",
    degree: "management",
    level: "degree",
    formula: "T = 0.1 * GAA + max(0.6 * F + 0.2 * max(Qz1, Qz2), 0.4 * F + 0.2 * Qz1 + 0.3 * Qz2)",
    formFields: [
      { id: "GAA", label: "GAA", description: "Graded Assignment Average", max: 100 },
      { id: "Qz1", label: "Quiz 1", description: "First Quiz Score", max: 100 },
      { id: "Qz2", label: "Quiz 2", description: "Second Quiz Score", max: 100 },
      { id: "F", label: "Final Exam", description: "Final Examination Score", max: 100 },
    ],
  },
]